# Generated by Django 4.1.3 on 2022-11-13 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondencia',
            old_name='estado',
            new_name='entregado',
        ),
    ]
