# Generated by Django 4.1.3 on 2022-11-13 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_correspondencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondencia',
            name='propietario',
        ),
    ]
